apiVersion: v1
kind: Service
metadata:
 name: svc-portal-noticias
spec:
 type: NodePort
 selector:
  app: portal-noticias
 ports:
  name: htpp-port
  port: 83
  targetPort: 82
  # nodePort: 30083 # Optional: specific NodePort value

